# Generated by Django 2.2.1 on 2019-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0004_auto_20190620_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_signin_info',
            name='user',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.DeleteModel(
            name='users_signin_info',
        ),
    ]
