# Generated by Django 2.2.1 on 2019-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0005_auto_20190622_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharma',
            name='pin',
        ),
        migrations.AlterField(
            model_name='pharma',
            name='location_address_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='pharma_signin_info',
        ),
    ]
