# Generated by Django 2.2.1 on 2019-06-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0006_auto_20190622_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharma',
            name='activated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='authentication_file',
            field=models.FileField(blank=True, upload_to='authentication_files/'),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='email',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='location_address_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='password',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
