# Generated by Django 2.2.1 on 2019-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0007_auto_20190622_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharma',
            name='email',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='location_address_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='organization_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
