# Generated by Django 2.2.1 on 2019-06-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0010_auto_20190622_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharma',
            name='entry_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pharma',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='signin_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signin_datetime', models.DateTimeField(auto_now_add=True)),
                ('signout_datetime', models.DateTimeField(blank=True)),
                ('pharmaceutical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm_app.pharma')),
            ],
        ),
    ]
