# Generated by Django 2.2.1 on 2019-06-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0011_auto_20190622_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharma',
            name='entry_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
