# Generated by Django 2.2.1 on 2019-06-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0014_auto_20190622_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='download_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=206)),
                ('file_path', models.CharField(max_length=228)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('expiry_datetime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
