# Generated by Django 2.2.1 on 2019-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0015_download_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='download_record',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
