# Generated by Django 2.2.1 on 2019-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0016_download_record_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=50)),
                ('medicine', models.CharField(max_length=300)),
                ('info', models.CharField(max_length=500)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='medicine_composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.CharField(max_length=300)),
                ('weightage', models.DecimalField(decimal_places=4, max_digits=4)),
                ('medicine', models.ForeignKey(on_delete='CASCADE', to='pharm_app.medicine_info')),
            ],
        ),
    ]
