# Generated by Django 2.2.1 on 2019-06-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0017_medicine_composition_medicine_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine_info',
            name='added_composition',
            field=models.BooleanField(default=False),
        ),
    ]
