# Generated by Django 2.2.1 on 2019-06-24 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0020_auto_20190624_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_composition',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm_app.medicine_info'),
        ),
    ]
