# Generated by Django 2.2.1 on 2019-06-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm_app', '0021_auto_20190624_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='keys_key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('token', models.IntegerField()),
            ],
        ),
    ]
